language: php

php:
  - 5.5
  - 5.6

sudo: false

env:
  matrix:
    - DB=sqlite db_dsn='sqlite:///:memory:'
  global:
    - DEFAULT=1

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

  fast_finish: true

  include:
    - php: 5.5
      env: PHPCS=1 DEFAULT=0

    - php: hhvm
      env: HHVM=1 DB=sqlite db_dsn='sqlite:///:memory:'

    - php: hhvm-nightly
      env: HHVM=1 DB=mysql db_dsn='mysql://travis@0.0.0.0/cakephp_test'

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

  - sh -c "if [ '$PHPCS' = '1' ]; then composer require 'cakephp/cakephp-codesniffer:dev-master'; fi"

  - phpenv rehash
  - set +H
  - cp phpunit.xml.dist phpunit.xml

script:
  - sh -c "if [ '$DEFAULT' = '1' ]; then phpunit --stderr; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests ./config ./webroot; fi"

notifications:
  email: false